name: PHP CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: PHP installieren
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Composer installieren
        run: composer install

      - name: PHPUnit Tests ausführen
        run: composer test